### ISSUE TITLE
IP camera IP address

### ISSUE THREAD

**Issue by babashunsuke** [lumeohq/onvif-rs#89]
IP camera may have multiple IP addresses. e.g. Link local and DHCP (IPv4). However the ONVIF library returns one of them.

**Comment by Alibirb** [comment]
I think this may have been fixed in https://github.com/lumeohq/onvif-rs/commit/81f145c792d1ba429778cd821635be6913fb1bb9

The `url` field was changed to `urls` and turned into a `Vec`. I'm currently trying to get one of my cameras to actually report multiple URLs so I can verify this (and test that my own application handles it appropriately).

**Comment by SamuelYvon** [comment]
I use this library extensively. It reports multiple URLs properly on my end.
